# site settings
title: Urbanismo
subtitle: Social
email: spurbanismo@spurbanismo.sp.gov.br
description: Nosso site governamental é o ponto de partida para explorar e compreender a evolução dinâmica da maior metrópole do Brasil. Aqui, você encontrará informações abrangentes sobre o planejamento urbano, desenvolvimento sustentável e as iniciativas que moldam o cenário urbano de São Paulo.
baseurl: "/urbanismo-social" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Viaduto do chá, 15
city: São Paulo
state: SP
zip_code: +55
country: Brasil
phone: (11) xxx-xxxx

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# deployment
host: 0.0.0.0
port: 5000

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/smul_sp/
  LinkedIn:  https://www.linkedin.com/company/smulsp
  Twitter: https://twitter.com/smul_sp
  Facebook: https://www.facebook.com/smulsp
  Youtube: https://www.youtube.com/user/pmspsmdu

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
